#!/bin/bash
#set -e
echo "#####################################"
echo "TimeShift For EXT4 User"
echo "#####################################"
echo "Update your System "
echo "#################################"
paru -Syyu
echo
echo
echo "Installing Packages"
echo "#####################################"
paru --noconfirm -S timeshift
echo
echo "#####################################"
echo "Done Rebooting! "
echo "#####################################"
Sleep 3
reboot
