#!/bin/bash
#set -e
echo "#################################"
echo "Configuring Snapper "
echo "#################################"
echo
echo "Installing Packages"
echo "#################################"
paru -S btrfs-progs grub-btrfs snapper snapper-gui-git snap-pac-grub xerolinux-rollback-git --noconfirm
echo
echo
sleep 2
echo "Cleaning up before install"
echo "#################################"
sudo umount /.snapshots
sudo rm -rf /.snapshots
echo
echo "Creating Config"
echo "#################################"
sudo snapper -c root create-config /
echo
echo "Cleaning up Subvolumes"
echo "#################################"
sudo btrfs subvolume delete /.snapshots
echo
echo "Creating required directory"
echo "#################################"
sudo mkdir /.snapshots
echo
echo "Configuring Permissions"
echo "#################################"
sudo chmod a+rx /.snapshots
sudo chmod 750 /.snapshots
sudo chown :wheel /.snapshots
echo
echo "Mounting Subvolumes"
echo "#################################"
sudo mount -a
echo
echo "Configuring Snapper Config"
echo "#################################"
snapperConfig='/etc/snapper/configs/root'
# Put the username in line 21
sudo sed -i "s/^ALLOW_USERS.*/ALLOW_USERS=\"$(whoami)\"/g" $snapperConfig
# Change TIMELINE Scheme as Arch Wiki Suggestion
sudo sed -i "s/^TIMELINE_LIMIT_YEARLY=.*/TIMELINE_LIMIT_YEARLY=\"0\"/g" $snapperConfig
sudo sed -i "s/^TIMELINE_LIMIT_MONTHLY=.*/TIMELINE_LIMIT_MONTHLY=\"0\"/g" $snapperConfig
sudo sed -i "s/^TIMELINE_LIMIT_WEEKLY=.*/TIMELINE_LIMIT_WEEKLY=\"0\"/g" $snapperConfig
sudo sed -i "s/^TIMELINE_LIMIT_DAILY=.*/TIMELINE_LIMIT_DAILY=\"7\"/g" $snapperConfig
sudo sed -i "s/^TIMELINE_LIMIT_HOURLY=.*/TIMELINE_LIMIT_HOURLY=\"5\"/g" $snapperConfig
echo
echo "Enabling Snapper Services"
echo "#################################"
sudo systemctl enable --now snapper-timeline.timer
sudo systemctl enable --now snapper-cleanup.timer
sudo systemctl enable --now grub-btrfs.path
echo
echo "Creating Initial Snap"
echo "#################################"
sudo snapper -c root create -c timeline --description "Fresh Install"
echo
echo "Finally Updating Grub"
echo "#################################"
sudo grub-mkconfig -o /boot/grub/grub.cfg
echo
echo "#################################"
echo " Done !  Rebooting for good measure"
echo "#################################"
sleep 2
sudo reboot
