#!/bin/bash
#set -e
echo "Update your System "
echo "#################################"
paru -Syyu
echo
echo
echo "#####################################"
echo "TimeShift with Sutosnap & Grub -BTRFS"
echo "#####################################"
echo
echo "Installing Packages"
echo "#####################################"
paru --noconfirm -S grub-btrfs timeshift timeshift-autosnap
echo
echo "Enabling Grub-BTRFS Services"
echo "#####################################"
sudo systemctl enable --now grub-btrfs.path
echo
echo "#####################################"
echo "Done ! "
echo "#####################################"
echo
echo "Rebooting To Activate ! "
echo "#####################################"
sleep 2
sudo reboot
