#!/usr/bin/env -S python
import os
import sys
import subprocess as sp
from qtpy.QtGui import *
from qtpy.QtWidgets import *
from qtpy.QtCore import *
import qdarkstyle
import psutil

# Depends
# python-pyqt5 python-qdarkstyle python-psutil

# Current version
current_version = '0.1.2'


class Filesystem:

    @staticmethod
    def getFsType():
        partitions = psutil.disk_partitions()
        fstype = 'unknow'
        for partition in partitions:
            if partition.mountpoint == '/':
                fstype = partition.fstype
                break

        return fstype

    @staticmethod
    def isSnapperPresent():
        retValue = False
        outputStatus = sp.getstatusoutput('which snapper')
        if outputStatus[0] == 0:
            retValue = True

        return retValue

    @staticmethod
    def isTimeshiftPresent():
        retValue = False
        outputStatus = sp.getstatusoutput('which timeshift')
        if outputStatus[0] == 0:
            retValue = True

        return retValue


class Version:

    @staticmethod
    def getAppName():
        return 'Xerolinux Filesystem Tool'

    @staticmethod
    def getVersion():
        return current_version


class mainWindow(QMainWindow):
    app = QApplication(sys.argv)
    verticalLayout = QVBoxLayout()
    messageLabel = QLabel()
    runConfigureSnapperPushButton = QPushButton('Configure Snapper')
    runConfigureTimeshiftPushButton = QPushButton('Configure Timeshift')
    runXerolinuxRollbackPushButton = QPushButton('run Xerolinux Rollback Tool')
    runTimeshiftPushButton = QPushButton('run Timeshift')


    def __init__(self):
        super().__init__(parent=None)
        self.app.setStyleSheet(qdarkstyle.load_stylesheet())
        self.setWindowTitle(f'Xerolinux Rollback Utility v. {Version.getVersion()}')
        self.setFixedSize(QSize(640, 480))
        ############
        # Title
        self.setWindowTitle(f'{Version.getAppName()} v.{Version.getVersion()}')
        self.setWindowIcon(QIcon('./images/xerolinux-icon.png'))
        ###################################################
        # Vertical Default Layout ###
        self.verticalLayout.setAlignment(Qt.AlignTop)
        ####
        # Message Label
        self.verticalLayout.addWidget(self.messageLabel)
        ###
        # Set the central widget of the Window.
        centralWidget = QWidget()
        centralWidget.setLayout(self.verticalLayout)
        self.setCentralWidget(centralWidget)
        ###
        # Setup UI
        self.initUI()
        ############
        # setup stylesheet
        # the default system in qdarkstyle uses qtpy environment variable
        self.show()
        self.centerMe()
        #####
        sys.exit(self.app.exec())


    def initUI(self):
        self.messageLabel.setAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.messageLabel.setText(f'You are using {Filesystem.getFsType()} filestystem.')
        if Filesystem.getFsType() == 'btrfs':
            if Filesystem.isSnapperPresent():
                self.runXerolinuxRollbackPushButton.clicked.connect(self.xerolinuxRollbackClick)
                self.verticalLayout.addWidget(self.runXerolinuxRollbackPushButton)
            else:
                self.verticalLayout.addWidget(self.runConfigureSnapperPushButton)
        else:
            print('filesystem is ext4')
            if Filesystem.isTimeshiftPresent():
                self.verticalLayout.addWidget(self.runTimeshiftPushButton)
            else:
                self.verticalLayout.addWidget(self.runConfigureTimeshiftPushButton)

    @staticmethod
    def xerolinuxRollbackClick():
        sp.getoutput('xerolinux-rollback')


    @staticmethod
    def configureSnapperClick():
        sp.getoutput('konsole --hide-menubar --hide-tabbar -e /usr/local/share/xerolinux-filesystem-tool-git/configure-snapper')


    @staticmethod
    def configureTimeshiftBtrfsClick()
        sp.getoutput('ls -la')


    @staticmethod
    def runTimeshiftClick():
        sp.getoutput('timeshift')


    @staticmethod
    def configureTimeshiftClick():
        sp.getoutput('')



    def centerMe(self):
        qtRectangle = self.frameGeometry()
        centerPoint = QDesktopWidget().availableGeometry().center()
        qtRectangle.moveCenter(centerPoint)
        self.move(qtRectangle.topLeft())

    def exitApp(self):
        self.app.quit()
        sys.exit(0)


if __name__ == '__main__':
    os.environ['QT_LOGGING_RULES'] = "qt5ct.debug=false"
    os.environ['QT_API'] = 'pyqt5'
    window = mainWindow()
