#!/bin/bash
#set -e
echo "#####################################"
echo "TimeShift For EXT4 User"
echo "#####################################"
echo "Update your System "
echo "#################################"
paru -Syyu
echo
echo
echo "Installing Packages"
echo "#####################################"
sudo pacman -S timeshift --noconfirm
echo
echo "#####################################"
echo "Done ! "
echo "#####################################"
Sleep 3
